server:
  port: 8100
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000



zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    io-devices-service:
      path: /io-devices/**
      serviceId: io-devices-service
      stripPrefix: false
      sensitiveHeaders:
