version: '2.1'
services:
  rabbitmq-mqtt:
    image: rabbitmq-mqtt
    hostname: localhost
    restart: always
    ports:
      - "15672:15672"
      - "15675:15675"
      - "1883:1883"

  config-service:
    image: config-service
    restart: always
    ports:
      - "8101:8101"
    depends_on:
      - rabbitmq-mqtt


  registry:
    image: registry
    restart: always
    ports:
      - "8761:8761"
    links:
      - config-service
    depends_on:
      - config-service

  gateway-service:
    image: gateway-service
    restart: always
    ports:
      - "8100:8100"
    links:
      - config-service
      - rabbitmq-mqtt
    depends_on:
      - registry

  inner-sensor-simulator:
    image: inner-sensor-simulator
    restart: always
    ports:
      - "8102:8102"
    links:
      - config-service
      - rabbitmq-mqtt
    depends_on:
      - gateway-service

