version: '2.1'
services:
  rabbitmq:
    image: dimka0586/rabbitmq-mqtt
    restart: always
    ports:
      - 15672:15672
      - 15675:15675
      - 1883:1883
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-service:
    image: dimka0586/config-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: dimka0586/registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    image: dimka0586/gateway-service
    restart: always
    ports:
      - 80:8100
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  
  inner-sensor-simulator:
    image: dimka0586/inner-sensor-simulator
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"