spring:
  application:
    name: gateway-service

server:
  port: 8100

zuul:
  routes:
    io-devices-service:
      path: /io-devices-service/**
      serviceId: io-devices-service

ribbon:
  eureka:
    enabled: false

io-devices-service:
  ribbon:
    listOfServers: localhost:8110